version: '3.8'

services:
  postgres:
    container_name: postgres_mtcg
    image: postgres:15
    ports:
      - "5433:5432"
    volumes: 
      - mtcg_db:/var/lib/postgres/data 
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mtcg
volumes:
  mtcg_db:
